In [1]:
import pandas as pd
import re

In [2]:
df1=pd.read_csv('flipkart_product.csv', encoding='latin-1')
df=df1.copy()

In [3]:
print(df.shape)
print(df.columns)
print(df.head())

(14168, 5)
Index(['ProductName', 'Price', 'Rate', 'Review', 'Summary'], dtype='object')
                                         ProductName     Price  Rate  \
0  Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...  ??3,999   5.0
1  Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...  ??3,999   5.0
2  Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...  ??3,999   3.0
3  Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...  ??3,999   1.0
4  Candes 12 L Room/Personal Air Cooler?ÿ?ÿ(White...  ??3,999   3.0

            Review                                            Summary
0           Super!  Great cooler.. excellent air flow and for this...
1          Awesome             Best budget 2 fit cooler. Nice cooling
2             Fair  The quality is good but the power of air is de...
3  Useless product                 Very bad product it's a only a fan
4             Fair                                      Ok ok product

In [4]:
df['ProductName']=df['ProductName'].apply(lambda x: re.sub(r'[^\x00-\x7F]','',str(x)).split())

In [5]:
df

,ProductName,Price,Rate,Review,Summary
0,"[Candes, 12, L, Room/Personal, Air, Cooler??(W...","??3,999",5.0,Super!,Great cooler.. excellent air flow and for this...
1,"[Candes, 12, L, Room/Personal, Air, Cooler??(W...","??3,999",5.0,Awesome,Best budget 2 fit cooler. Nice cooling
2,"[Candes, 12, L, Room/Personal, Air, Cooler??(W...","??3,999",3.0,Fair,The quality is good but the power of air is de...
3,"[Candes, 12, L, Room/Personal, Air, Cooler??(W...","??3,999",1.0,Useless product,Very bad product it's a only a fan
4,"[Candes, 12, L, Room/Personal, Air, Cooler??(W...","??3,999",3.0,Fair,Ok ok product
...,...,...,...,...,...
14163,"[Eurodomo, Hood, Indigo, PRO, HC, SC, FL, BK, ...","??7,599",4.0,Pretty good,Chimney is really good the only issue is brand...
14164,"[Eurodomo, Hood, Indigo, PRO, HC, SC, FL, BK, ...","??7,599",4.0,Good choice,Functions really very good and the features ar...
14165,"[Eurodomo, Hood, Indigo, PRO, HC, SC, FL, BK, ...","??7,599",4.0,Good choice,"Installation done, now let's see how it worksP..."
14166,"[Eurodomo, Hood, Indigo, PRO, HC, SC, FL, BK, ...","??7,599",5.0,Very much safisfactory product.,"using the product for past 2.5 months, working..."
14167,"[Eurodomo, Hood, Indigo, PRO, HC, SC, FL, BK, ...",NaN,NaN,NaN,NaN

In [6]:
df['Price']=df['Price'].astype(str).apply(lambda x: re.sub(r'[^\d]','', x))
df['Price']=pd.to_numeric(df['Price'], errors='coerce')

In [7]:
df['Rate']= pd.to_numeric(df['Rate'], errors='coerce')

In [8]:
df.dropna(subset=['Review', 'Rate'], inplace=True)

In [9]:
df.reset_index(drop=True, inplace=True)

In [10]:
print(df.shape)
print(df.dtypes)
print(df.head())

(14167, 5)
ProductName     object
Price          float64
Rate           float64
Review          object
Summary         object
dtype: object
                                         ProductName   Price  Rate  \
0  [Candes, 12, L, Room/Personal, Air, Cooler??(W...  3999.0   5.0
1  [Candes, 12, L, Room/Personal, Air, Cooler??(W...  3999.0   5.0
2  [Candes, 12, L, Room/Personal, Air, Cooler??(W...  3999.0   3.0
3  [Candes, 12, L, Room/Personal, Air, Cooler??(W...  3999.0   1.0
4  [Candes, 12, L, Room/Personal, Air, Cooler??(W...  3999.0   3.0

            Review                                            Summary
0           Super!  Great cooler.. excellent air flow and for this...
1          Awesome             Best budget 2 fit cooler. Nice cooling
2             Fair  The quality is good but the power of air is de...
3  Useless product                 Very bad product it's a only a fan
4             Fair                                      Ok ok product

In [11]:
df['ProductName']=df['ProductName'].apply(lambda x:' '.join(x) if isinstance(x, list) else str(x))
print(df['ProductName'].head())

0    Candes 12 L Room/Personal Air Cooler??(White, ...
1    Candes 12 L Room/Personal Air Cooler??(White, ...
2    Candes 12 L Room/Personal Air Cooler??(White, ...
3    Candes 12 L Room/Personal Air Cooler??(White, ...
4    Candes 12 L Room/Personal Air Cooler??(White, ...
Name: ProductName, dtype: object

In [12]:
print(type(df['ProductName'][0]))
print(repr(df['ProductName'][0]))

<class 'str'>
'Candes 12 L Room/Personal Air Cooler??(White, Black, Elegant High Speed-Honey Comb Cooling Pad & Ice Chamber, Blower)'

In [13]:
df['ProductName']= df['ProductName'].apply(lambda x: re.sub(r'\?+', '', str(x)))

In [14]:
df['ProductName']

0        Candes 12 L Room/Personal Air Cooler(White, Bl...
1        Candes 12 L Room/Personal Air Cooler(White, Bl...
2        Candes 12 L Room/Personal Air Cooler(White, Bl...
3        Candes 12 L Room/Personal Air Cooler(White, Bl...
4        Candes 12 L Room/Personal Air Cooler(White, Bl...
                               ...
14162    Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...
14163    Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...
14164    Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...
14165    Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...
14166    Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...
Name: ProductName, Length: 14167, dtype: object

In [15]:
df

,ProductName,Price,Rate,Review,Summary
0,"Candes 12 L Room/Personal Air Cooler(White, Bl...",3999.0,5.0,Super!,Great cooler.. excellent air flow and for this...
1,"Candes 12 L Room/Personal Air Cooler(White, Bl...",3999.0,5.0,Awesome,Best budget 2 fit cooler. Nice cooling
2,"Candes 12 L Room/Personal Air Cooler(White, Bl...",3999.0,3.0,Fair,The quality is good but the power of air is de...
3,"Candes 12 L Room/Personal Air Cooler(White, Bl...",3999.0,1.0,Useless product,Very bad product it's a only a fan
4,"Candes 12 L Room/Personal Air Cooler(White, Bl...",3999.0,3.0,Fair,Ok ok product
...,...,...,...,...,...
14162,Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...,7599.0,1.0,Worthless,After 6th months of use I am reviewing honesty...
14163,Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...,7599.0,4.0,Pretty good,Chimney is really good the only issue is brand...
14164,Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...,7599.0,4.0,Good choice,Functions really very good and the features ar...
14165,Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...,7599.0,4.0,Good choice,"Installation done, now let's see how it worksP..."
14166,Eurodomo Hood Indigo PRO HC SC FL BK 60 Auto C...,7599.0,5.0,Very much safisfactory product.,"using the product for past 2.5 months, working..."

In [16]:
def label_sentiment(rate):
  if rate>=4.0:
    return 'Positive'
  elif rate==3:
    return 'Neutral'
  else:
    return 'Negative'
df['Sentiment']=df['Rate'].apply(label_sentiment)

In [17]:
print(df['Sentiment'].value_counts())

Sentiment
Positive    10875
Negative     1985
Neutral      1307
Name: count, dtype: int64

In [18]:
import nltk
nltk.download('vader_lexicon')
from nltk.sentiment.vader import SentimentIntensityAnalyzer

[nltk_data] Downloading package vader_lexicon to /root/nltk_data...

In [19]:
sia=SentimentIntensityAnalyzer()

In [20]:
df['compound_score']=df['Review'].astype(str).apply(lambda x: sia.polarity_scores(x)['compound'])

In [21]:
def vader_label(score):
  if score >= 0.05:
    return 'Positive'
  elif score <= -0.05:
    return 'Negative'
  else:
    return 'Neutral'
df['VADER_Sentiment']= df['compound_score'].apply(vader_label)

print("VADER Sentiment Distribution:")
print(df['VADER_Sentiment'].value_counts())

VADER Sentiment Distribution:
VADER_Sentiment
Positive    10819
Neutral      2044
Negative     1304
Name: count, dtype: int64

In [22]:
print(df[['Review', 'Sentiment', 'VADER_Sentiment']].head(10))

               Review Sentiment VADER_Sentiment
0              Super!  Positive        Positive
1             Awesome  Positive        Positive
2                Fair   Neutral        Positive
3     Useless product  Negative        Negative
4                Fair   Neutral        Positive
5             Awesome  Positive        Positive
6  Highly recommended  Positive        Positive
7                Nice   Neutral        Positive
8      Unsatisfactory  Negative         Neutral
9     Worth the money  Positive        Positive

In [23]:
print("VADER Sentiment Distribution:")
print(df['VADER_Sentiment'].value_counts())
print("\n Star Rating Sentiment Distribution:")
print(df['Sentiment'].value_counts())

VADER Sentiment Distribution:
VADER_Sentiment
Positive    10819
Neutral      2044
Negative     1304
Name: count, dtype: int64

 Star Rating Sentiment Distribution:
Sentiment
Positive    10875
Negative     1985
Neutral      1307
Name: count, dtype: int64

In [24]:
import sqlite3
conn=sqlite3.connect('flipkart_reviews.db')
df.to_sql('reviews', conn, if_exists='replace', index=False)
print("\n Total rows in database:")
print(pd.read_sql("Select Count(*) as total_rows From reviews", conn))

 Total rows in database:
   total_rows
0       14167

Sentiment Distribution

In [25]:
q1= pd.read_sql(""" Select Sentiment, COUNT(*) as total
From reviews group by sentiment order by total desc""", conn)
print("Sentiment Distribution:")
print(q1)

Sentiment Distribution:
  Sentiment  total
0  Positive  10875
1  Negative   1985
2   Neutral   1307

Top 10 most reviewed products

In [26]:
q2=pd.read_sql("""Select ProductName, Count(*) as review_count,
Round(avg(Rate),2) as avg_rating from reviews
Group by ProductName order by review_count DESC LIMIT 10 """,conn)
print("Top 10 Most Reviewed Products:")
print(q2)

Top 10 Most Reviewed Products:
                                         ProductName  review_count  avg_rating
0  Cosito 144 TC Cotton Double Floral Flat Bedshe...          2322        4.12
1  Canon EOS 3000D DSLR Camera 1 Camera Body, 18 ...          1830        4.48
2  RIAN Animal Single Mink Blanket for Mild Winte...          1398        4.16
3  Crompton 75 L Desert Air Cooler(White, Teal, A...          1183        4.08
4  CLOTHOLOGY 144 TC Cotton Double Printed Flat B...          1135        3.96
5  FLIPZON Baby 6 Shelve Unbreakable Material PVC...          1010        4.40
6  MAHARAJA WHITELINE 65 L Desert Air Cooler(Whit...           780        4.12
7  Hindware Ripple 90 Auto Clean Wall Mounted Chi...           567        4.23
8  METRO LIVING 104 TC Cotton Double Animal Flat ...           385        3.79
9  Hindware Nevio Plus 60 Auto Clean Wall Mounted...           310        4.55

In [27]:
df.columns

Index(['ProductName', 'Price', 'Rate', 'Review', 'Summary', 'Sentiment',
       'compound_score', 'VADER_Sentiment'],
      dtype='object')

In [28]:
q3=pd.read_sql(""" Select Count(*) as mismatches
from reviews where Sentiment!= VADER_Sentiment """,conn)
print("Total Mismatches between starrating and Vader")
print(q3)

Total Mismatches between starrating and Vader
   mismatches
0        2825

In [29]:
df.to_csv('reviews_for_powerbi.csv', index=False)
q1.to_csv('sentiment_distribution.csv', index=False)
q2.to_csv('top_products.csv', index=False)
print('All files exported successfully')
from google.colab import files
files.download('reviews_for_powerbi.csv')
files.download('sentiment_distribution.csv')
files.download('top_products.csv')

All files exported successfully